name: Checkmarx Cx-Flow Scan
on:
  push:
    branches:
      - main
      - master

  pull_request:
    types: [opened, reopened, synchronize] #Types specify which pull request events will trigger the workflow. For more events refer Github Actions documentation.
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    # Runs the Checkmarx Scan leveraging the latest version of CxFlow - REFER to Action README for list of inputs
      - name: Checkmarx CxFlow Action
        uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.9
        with:
          project: ${{ github.repository }}-PR
          team: /CxServer/SP/Partners/NSecurity
          checkmarx_url: https://cxprivatecloud.checkmarx.net
          checkmarx_username: mark.feferman@checkmarx.com
          checkmarx_password: ${{ secrets.CXSAST_PWD }}
          checkmarx_client_secret: ${{ secrets.CXSAST_CLIENT_SECRET }}
          scanners: sast,sca
          break_build: false
          bug_tracker: GitHub
          sca_api_url: https://api-sca.checkmarx.net
          sca_app_url: https://sca.checkmarx.net
          sca_access_control_url: https://platform.checkmarx.net
          sca_tenant: sca-champions
          sca_username: afeferman
          sca_password: ${{ secrets.CXSCA_PWD }}
          params: '--namespace=${{ github.repository_owner }} --repo-name=${{ github.event.repository.name }} --branch=${{ github.ref }} --merge-id=${{ github.event.number }} --logging.level.com.checkmarx.*=DEBUG --cx-flow.filterSeverity --cx-flow.filterCategory'
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: cx.sarif
