name: Checkmarx Cx-Flow Scan
on:
  push:
    branches:
      - main
      - master
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    # Runs the Checkmarx Scan leveraging the latest version of CxFlow - REFER to Action README for list of inputs
      - name: Checkmarx CxFlow Action
        uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.9
        with:
          project: ${{ github.repository }}-PR
          team: /CxServer
          checkmarx_url: http://ec2amaz-exteng
          checkmarx_username: mfeferman
          checkmarx_password: Checkmarx#1
          checkmarx_client_secret: 014DF517-39D1-4453-B7B3-9930C563627C
          scanners: sast
          break_build: false
          bug_tracker: github
          # sca_api_url: ${{ secrets.SCA_API_URL }}
          # sca_app_url: ${{ secrets.SCA_APP_URL }}
          # sca_access_control_url: ${{ secrets.SCA_ACCESS_CONTROL_URL }}
          # sca_tenant: ${{  secrets.SCA_TENANT }}
          # sca_username: ${{ secrets.SCA_USERNAME }}
          # sca_password: ${{ secrets.SCA_PASSWORD }}
          params: '--namespace=${{ github.repository_owner }} --repo-name=${{ github.event.repository.name }} --branch=${{ github.ref }} --merge-id=${{ github.event.number }} --logging.level.com.checkmarx.*=DEBUG --cx-flow.filterSeverity --cx-flow.filterCategory'
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: cx.sarif
